# Values here will overwrite values.yaml defaults. These values are used when deploying locally to minikube

app:
  uwsgi:
    processes: 2
    autoreload: 1
    disableLogging: false

apm:
  datadog_env: local

affinity:

resourceLimits:
  enable: false

redis:
  create: true
  port: 6379
  containerPort: 6379

elasticsearch:
  create: true
  populate: true
  id: 1000
  port: 9200
  containerPort: 9200
  storage: 1Gi
